name: bloc_base
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  easy_localization: ^3.0.1
  easy_localization_loader: ^1.0.0
  freezed_annotation: ^2.1.0
  flutter_bloc: ^8.1.1
  loading_animation_widget: ^1.2.0+3
  hive: ^2.2.3
  get_it: ^7.2.0
  google_fonts: ^3.0.1
  dio: ^4.0.6
  pretty_dio_logger: ^1.2.0-beta-1
  mocktail: ^0.3.0
  flutter_form_builder: ^7.6.0
  path_provider: ^2.0.11
  json_annotation: ^4.6.0
  form_builder_validators: ^8.3.0
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  freezed: ^2.1.0+1
  json_serializable: ^6.3.1
  build_runner: ^2.2.0
  flutter_gen_runner: ^4.3.0
  hive_generator: ^1.1.3

flutter:
  uses-material-design: true
  assets:
    - assets/locales/
    - assets/images/
    - assets/icons/
    - assets/fonts/

flutter_gen:
  output: lib/global/assets
  line_length: 80

  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
